<?php //echo "<pre>";print_r($this->client); ?>
<div><h2>Purchaser Information</h2></div>
<div width="100%" style="padding-top:30px;">
<div class="basGrid" style="width:50%;float:left;" >
    <table>
        <thead>
            <th colspan="2">Suite Information</th>
            
        </thead>
		<tr>
            <td>Project Name</td>
            <td><?php echo $this->client->project_name;?></td>
        </tr>
        <tr>
            <td>Suite #</td>
            <td><?php echo $this->client->suit_number?></td>
        </tr>
        <tr>
            <td>Suite Unit #</td>
            <td><?php echo $this->client->unit_number?></td>
        </tr>
        <tr>
            <td>Suite Level #</td>
            <td><?php echo $this->client->suit_level?></td>
        </tr>
        <tr>
            <td>Park #</td>
            <td><?php echo $this->client->parking_number?></td>
        </tr>
		<tr>
            <td>Park Unit #</td>
            <td><?php echo $this->client->parking_unit_number?></td>
        </tr>
		<tr>
            <td>Park Level #</td>
            <td><?php echo $this->client->parking_level_number?></td>
        </tr>
		<tr>
            <td>Locker #</td>
            <td><?php echo $this->client->locker_number?></td>
        </tr>
		<tr>
            <td>Locker Unit #</td>
            <td><?php echo $this->client->locker_unit_number?></td>
        </tr>
		<tr>
            <td>Locker Level #</td>
            <td><?php echo $this->client->locker_level_number?></td>
        </tr>
		<tr>
            <td>Price</td>
            <td><?php echo '$'.$this->client->purchase_price; ?></td>
        </tr>
        
    </table>
</div>
<div style="float:right;width:50%"  class="basGrid">
	<table>
        <thead>
            <th colspan="2">Personal Information</th>
            
        </thead>
        <tr>
            <td>Name </td>
            <td><?php echo $this->client->first_name.' ' .$this->client->last_name ;?></td>
        </tr>
        <tr>
            <td>E-mail</td>
            <td><?php echo $this->client->email_address; ?></td>
        </tr>
        <tr>
            <td>Phone #</td>
            <td><?php echo $this->client->phone_number;?></td>
        </tr>
        <tr>
            <td>Date Of Birth </td>
            <td><?php echo $this->client->date_of_birth; ?></td>
        </tr>
		
    </table>
</div>
</div>

