<?php $this->headTitle('Login'); ?>
<form method="post" action="<?php echo $this->baseUrl(); ?>/user/auth/index">
<table style="width:400px;height:200px;margin-top:20px;" cellspacing="0" cellpadding="5">
    <tr style="background-color:#800000;">
        <td nowrap><span style="font-size:30px;color:white;font-weight:bold;">Login</span></td>
        <td></td>
        <td align="right"><img src="<?php echo $this->baseUrl(); ?>/images/user_login.png" style="width:40px;"></td>
    </tr>
    <tr><td></td></tr>
    <tr>
        <td colspan="2"><?php echo $this->form->username->getLabel();?></td>
        <td colspan="2"><?php echo $this->form->username;?></td>
    </tr>
     <tr>
        <td colspan="2"><?php echo $this->form->password->getLabel();?></td>
        <td colspan="2"><?php echo $this->form->password;?></td>
    </tr>
    <tr><td></td></tr>
    <tr style="background-color:#800000;">
        <td colspan="3" style="font-size:30px;color:white;font-weight:bold;"><input type="submit" style="font-size:18px;" value="Login" /></td>
    </tr>
    <tr>
        <td colspan="3" nowrap><a href="<?php echo $this->baseUrl();?>/user/auth/forgot-password">Forgot password ?</a></td>
    </tr>
</table>
</form>
