<div class="header">
    <span style="float:left;">
            <a  style="display:none;"  href="<?php echo $this->baseUrl();?>/report/pdf/index?id=<?php echo $this->paymentData[0]['id']?>"><img src="<?php echo $this->baseUrl();?>/images/pdf.png"/></a>&nbsp;
            <a href="<?php echo $this->baseUrl();?>/report/csv/index2?id=<?php echo $this->paymentData[0]['id']?>"><img src="<?php echo $this->baseUrl();?>/images/xls.png"/></a>
    </span>
</div>  
<?php echo $this->render('pdf/client.phtml');?>
