<div class="header">
    <span style="float:left;">
            <a  style="display:none;"  href="<?php echo $this->baseUrl();?>/report/pdf/index?from_date=<?php echo $this->fromDate?>&to_date=<?php echo $this->toDate?>">
                <img src="<?php echo $this->baseUrl();?>/images/pdf.png"/>
            </a>&nbsp;
            <a href="<?php echo $this->baseUrl();?>/report/csv/index2?from_date=<?php echo $this->fromDate?>&to_date=<?php echo $this->toDate?>">
                <img src="<?php echo $this->baseUrl();?>/images/xls.png"/>
            </a>
    </span>
</div>  
<?php echo $this->render('pdf/client.phtml');?>
